# Form implementation generated from reading ui file '/Users/nguyenngocaithien/NguyenNgocAiThien_K234111417_K234111E/LearnQCheckBox/ui/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(498, 412)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBoxHinh = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxHinh.setGeometry(QtCore.QRect(40, 50, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.checkBoxHinh.setFont(font)
        self.checkBoxHinh.setObjectName("checkBoxHinh")
        self.labelHinh = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelHinh.setGeometry(QtCore.QRect(50, 90, 231, 171))
        self.labelHinh.setText("")
        self.labelHinh.setPixmap(QtGui.QPixmap("/Users/nguyenngocaithien/NguyenNgocAiThien_K234111417_K234111E/LearnQCheckBox/ui/../images/ic_noimage.png"))
        self.labelHinh.setScaledContents(True)
        self.labelHinh.setObjectName("labelHinh")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 498, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBoxHinh.setText(_translate("MainWindow", "Hiển thị/Ẩn hình"))
